- CONTRIBUTING.md
- README.md
Will conflict with #41. If that is merged in, will update this PR then
> Adding some contribution guidelines

- content/december-2014-meet-minutes.md
- content/november-2014-meet-minutes.md
- content/october-2014-meet-minutes.md
> Add summary to all meeting minutes.

- pelicanconf.py
- Updating <code>pelicanconf.py</code> for adding Google Analytics facility to ChennaiPy website.
This fixes Issue #51
> Include Google analytics tracking code

- pelicanconf.py
- publishconf.py
- Deleting analytics tracking id from <code>pelicanconf.py</code>
- Adding analytics tracking id in <code>publishconf.py</code>
> Updating analytics tracking id only on publishconf.py

- content/meetup-feb-2015.md
- content/pages/about.md
- content/workshop-feb-2015.md
- Adding new page for meetup 
- Adding new page for workshop
classifying the workshop under a `workshops` tag for easier access in the future
- Home page will show both under upcoming events
> Adding feb event and workshop

- content/january-2015-meet-minutes.md
Minutes contributed by S. P. Balamurugan.
> Added Jan meetup Minutes.

- content/january-2015-meet-minutes.md
> Adding video links to all JAN talks

- content/pages/team.md
> Adding video post prod. team

- content/pages/about.md
> End of march meetup

- content/march-2015-meet-minutes.md
> Adding March minutes

- content/pages/about.md
> End of april meetup

- content/meetup-may-2015.md
> Adding may meetup info

- content/may-2015-meet-minutes.md
@shrayasr @bravegnu May meetup minutes is added for your review
> may meetup minutes added

- content/pages/about.md
3 points,
1.links for slack,fb and june meetup 
2. target=_blank 
3.fork me strip
P.S: Don't have facebook group link.
> Details in descriptions

- content/june-2015-meet-minutes.md
> Small typo with my name

- content/meetup-july-2015.md
- content/pages/about.md
July meetup schedule is added to event page #89
> Event page is updated

- content/pages/about.md
July meetup information link on landing page is removed
> July Meetup Link on Landing page is removed

- content/july-2015-meet-minutes.md
July 2015 meetup minutes added
> Meetup minutes July 2015

- content/meetup-aug-2015.md
- content/pages/about.md
Added August Meetup page and updated it in the upcoming events.
> August Meetup is updated in events.

- content/pages/about.md
Upcoming Meetup tab removed Until Announced
> Upcoming Meetup tab removed

- content/july-2015-meet-minutes.md
Improvements to the July minutes, with formatting, spelling and grammar fixes.
> Formatting, spelling and grammar fixes.

- content/august-2015-meet-minutes.md
> Add August Minutes

- content/pages/about.md
> Update front page - Hiding the Past meetup Detail

- content/meetup-dec-2016.md
- content/pages/about.md
to display upcomming December meetup.
> December meetup page is added

- content/january-2017-meet-minutes.md
> Jan 2017 Meeting Minutes

- content/january-2017-meet-minutes.md
@bravegnu Fixed the issues that I had overlooked.
> Jan Meeting Minutes Erratum

- content/february-2017-meeting-minutes.md
Meeting minutes for Feb 2017. Leaving Chennai early in the morning tomorrow. Not in town till March 2nd. So in case there are any changes I'll make them on March 2. If changes are to be made immediately please feel free to make them :)
> February Meet Minutes
